### ISSUE TITLE
Teams -tilan luominen

### ISSUE THREAD

**Issue by suklaanen** [TVT23KMO-R4-Mobiilisovellusprojekti/2024-Q4-Mobiili#1]
TVT23KMO_R4_Snimi1_Snimi2_Snimi3_Snimi4_Snimi5

- mukaan kaikki opintojakson opettajat

Jokaiselle opintojakson osatoteutukselle tulee olla oma kanava nimillä:
- Projekti
- KehAndroid
- Matematiikka
- Liiketoiminta
- Viestintä

**Comment by MacStache** [comment]
Kanavat luotu, opettajat kutsutaan sitten kun ohjaava opettaja on selvillä.
